---
- name: Telecharge, installe et configure bind9
  hosts: bind
  remote_user: paris
  become_user: root

  roles:
    - sources     
    - admin  
    - ssh
    - network
    - paquets
    - resolv      
    - db

- import_playbook: primaire.yml
- import_playbook: secondaire.yml
- import_playbook: verif.yml
